# Change these first
owner: nubiamarket # Your GitHub organization or username, where this repository lives
repo: check-uptime # The name of this repository

sites:
  - name: Nubia Market
    url: https://nubiacentraldecompras.com
  - name: Versión de pruebas de Nubia Market
    url: https://pruebas.nubiacentraldecompras.com
  - name: Nueva versión de Nubia Market (Alfa)
    url: https://nubiamarket.testingapps.es/up
  - name: RG Bugaderies
    url: https://app.rgbugaderies.es/up
  - name: DEMO RG Bugaderies
    url: https://bugaderies.nubiamarket.com/up
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /check-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Servicios de Nubia Market
  introTitle: "Comprobación de estado de los servicios de Nubia Market"
  introMessage: En esta página se puede comprobar el estado de los servicios de Nubia Market, si se detecta cualquier incidencia o se necesitan monitorizar algún servicio, puede contactar con nosostros vía [correo electrónico](mailto:soporte@nubiamarket.com)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
